---
# group_vars/all.yml
ansible_ssh_private_key_file: ~/.ssh/jpuskar.pem
ansible_ssh_user: ubuntu
region: us-east-1
zone: us-east-1a
keypair: jpuskar
security_groups: atplanet_ansible-auto-scaling-tutorial
instance_type: t1.micro
volumes:
  - device_name: /dev/sda1
    device_type: gp2
    volume_size: 20
    delete_on_termination: true
