---
# roles/deploy/tasks/main.yml

- name: Install git
  apt:
    pkg: git
    state: present
    update_cache: yes
  become:  yes

- name: Create www directory
  file:
    path: /srv/www
    owner: ubuntu
    group: ubuntu
    state: directory
  become:  yes

- name: Clone repository
  git:
    repo: "https://github.com/atplanet/hello-world-express-app.git"
    dest: /srv/www/webapp
    version: master

- name: Install nodejs
  apt:
    pkg: nodejs
    state: present
    update_cache: yes
  become:  yes

- name: Install npm
  apt:
    pkg: npm
    state: present
    update_cache: yes
  become:  yes

- name: Install "express" node.js package.
  npm:
    name: express
    path: /srv/www/webapp
  become:  yes

- name: Install upstart
  apt:
    pkg: upstart
    state: present
  become: yes

- name: Create upstart directory
  file:
    path: /etc/upstart
    owner: ubuntu
    group: ubuntu
    state: directory
  become: yes

- name: Install upstart script
  copy:
    src: upstart.conf
    dest: /etc/init/webapp.conf
  become: yes

- name: Enable and start the application
  service:
    name: webapp
    enabled: yes
    state: restarted
  become:  yes
